FROM node:18.18.2

WORKDIR /root/test-actions/GITHUB_ACTIONS_FRONTEND

COPY package*.json ./

RUN npm i -f

COPY . .

RUN npm run build

# Expose port 3002
EXPOSE 3002

# Use environment variable for port in the start script
CMD ["sh", "-c", "PORT=3002 npm run start"]
