name: CI + CD with docker

on:
  workflow_dispatch:
  
jobs:
  Staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t test-actions_frontend:staging .
      
      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker stop test-actions_backend || true
            docker rm test-actions_backend || true
            docker pull test-actions_backend:latest
            docker run -d -p 5000:5000 --name test-actions_backend test-actions_backend:latest
           ## pm2 reload server --update-env

  Testing:
    runs-on: ubuntu-latest
    environment:
      name: testing
    needs: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t test-actions_frontend:testing .
      
      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker stop test-actions_frontend || true
            docker rm test-actions_frontend || true
            docker pull test-actions_frontend:latest
            docker run -d -p 3000:3000 --name test-actions_frontend test-actions_frontend:latest
           ## pm2 reload testing --update-env

  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
    needs: Testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t test-actions_frontend:production .
      
      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker stop test-actions_frontend || true
            docker rm test-actions_frontend || true
            docker pull test-actions_frontend:production
            docker run -d -p 3001:3001 --name test-actions_production test-actions_production:latest
           ## pm2 reload production --update-env
