name: CI + CD

on:
   workflow_dispatch:
   
jobs:
  staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: hadielearning
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build

  testing:
    runs-on: ubuntu-latest
    environment: testing
      needs: staging
      url: 'http://test1.hadielearning.com'
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: hadielearning
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build
            pm2 start "npm run dev" --name testing
  Production:
    runs-on: ubuntu-latest
    environment: Production
    needs: testing
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build
            pm2 start "npm run start" --name production
