name: CI + CD

on:
  workflow_dispatch:
  
jobs:
  Staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build

  testing:
    runs-on: ubuntu-latest
    environment: testing
    needs: Staging
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build
            pm2 start "npm run dev" --name testing

  Production:
    runs-on: ubuntu-latest
    environment: Production
    needs: testing
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build
            pm2 start "npm run start" --name production
      
      - name: Deploy Nginx Configuration
        run: |
          echo "server {
              server_name stest.hadielearning.com;
              location / {
                           proxy_pass http://127.0.0.1:3001;
                           proxy_http_version 1.1;
                           proxy_set_header Upgrade $http_upgrade;
                           proxy_set_header Connection 'upgrade';
                           proxy_set_header Host $host;
                           proxy_cache_bypass $http_upgrade;
               }
	     }" > nginx.conf
          scp nginx.conf root@109.205.178.167:/etc/nginx/conf.d/actions.conf
          ssh root@109.205.178.167 'ln -s /etc/nginx/conf.d/actions.conf
          ssh root@109.205.178.167 'nginx -s reload'
