name: CI + CD

on:
  workflow_dispatch:
  
jobs:
  Staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t test-actions_frontend:staging .
      
      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            docker stop test-actions_frontend_1 || true
            docker rm test-actions_frontend_1 || true
            docker pull test-actions_frontend:staging
            docker run -d -p 3000:3000 --name test-actions_frontend_1 test-actions_frontend:staging
            pm2 reload server --update-env

  Testing:
    runs-on: ubuntu-latest
    environment:
      name: testing
      url: 'actions.hadielearning.com'
    needs: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t test-actions_frontend:testing .
      
      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            docker stop test-actions_frontend_1 || true
            docker rm test-actions_frontend_1 || true
            docker pull test-actions_frontend:testing
            docker run -d -p 3000:3000 --name test-actions_frontend_1 test-actions_frontend:testing
            pm2 reload testing --update-env

  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'test2.hadielearning.com'
    needs: Testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Build Docker image
        run: docker build -t test-actions_frontend:production .
      
      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            docker stop test-actions_frontend_1 || true
            docker rm test-actions_frontend_1 || true
            docker pull test-actions_frontend:production
            docker run -d -p 3000:3000 --name test-actions_frontend_1 test-actions_frontend:production
            pm2 reload production --update-env
