name: CI + CD

on:
  workflow_dispatch:
  
jobs:
  Staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build

  testing:
    runs-on: ubuntu-latest
    environment: testing
    needs: Staging
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build
            pm2 start "npm run dev" --name testing

  Production:
    runs-on: ubuntu-latest
    environment: Poduction
    needs: testing
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build
            pm2 start "npm run dev" --name testing

