name: CI + CD

on:
  workflow_dispatch:
  
jobs:
  Staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            pm2 reload server --update-env

  Testing:
    runs-on: ubuntu-latest
    environment:
      name: testing
      url: 'actions.hadielearning.com'
    needs: Staging
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build
            pm2 reload testing --update-env

  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'test.hadielearning.com'
    needs: Testing
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.GIT_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build
            pm2 reload production --update-env
