name: Testing and Deployment

on:
  push:
    branches: [main]

jobs:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    needs: prompt_for_production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to install dependencies, run tests, etc.
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  deploy_staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build_and_test
    strategy:
      matrix:
        include:
          - proceed_to_production: false
    steps:
      - name: Deploy to staging
        if: needs.prompt_for_production.outputs.proceed_to_production == 'false'
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_BACKEND
            git pull
            npm install -f
            npm run build
            pm2 reload frontend-new --update-env
