name: Testing Frontend Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Type "DEPLOY" to confirm deployment to Production'
        required: true
        default: 'DEPLOY'

jobs:
  build:
    name: Testing Frontend Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build
            pm2 reload frontend --update-env

  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.confirm_deploy == 'DEPLOY' && github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: 109.205.178.167
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /root/test-actions/GITHUB_ACTIONS_FRONTEND
            git pull
            npm install -f
            npm run build
            pm2 reload frontend --update-env
